name: Lint on PR
on:
  pull_request:
    branches:
      - '**'
    
jobs:
  Continuous-Integration:
    name: Performs linting and formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run:  yarn install --legacy-peer-deps

      - name: Run linting check
        run:  yarn run lint:fix

      - name: Check formatting
        run:  yarn run format:fix